### ISSUE TITLE
calls to removeEventListener raise errors in Chrome

### ISSUE THREAD

**Issue by wesvetter** [caiogondim/blooming-menu#11]
Calling `removeEventListener` with one parameter raises an exception in Chrome (but not Safari).

The following code raises a `TypeError` in Chrome but nothing in Safari:

``` javascript
document.querySelector('body').removeEventListener('foo')
```

It seems that the calls to `removeEventListener` required a named function, otherwise they throw an error. This occurs in the `selectItem` call:

``` javascript
    var btnWrappers = document.querySelector('.' + self.props.CSSClassPrefix + ITEM_BTN_WRAPPER_CSS_CLASS)
    btnWrappers.addEventListener(animationEndEventName(), function () {
      self.close()

      self.props.elements.items.forEach(function (item) {
        item.style.display = 'none'
      })

      document
        .querySelector('.' + self.props.CSSClassPrefix + ITEM_BTN_WRAPPER_CSS_CLASS)
        .removeEventListener(animationEndEventName()) // <-- Requires 2 params
    })
```

There are calls to `removeEventListener` via `instance.remove()` too:

``` javascript
  function unbindEventListeners (self) {
    self.props.elements.main.removeEventListener('click')
    self.props.elements.main.removeEventListener('touchstart')
  }
```

These also throw errors in Chrome. This can be reproduced simply with:

``` javascript
var menu;
menu = new BloomingMenu({ itemsNum: 3 });
menu.render();
menu.remove();
```

I can work on a PR for this but just want to make sure I'm not missing something obvious about how the library or `removeEventListener` works.

**Comment by caiogondim** [comment]
Accordingly to https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener the code is indeed wrong. We should pass two params to `removeEventListener`.

If you can work on a PR that would be amazing.

Let me know if I can help you.

**Comment by caiogondim** [comment]
Will publish a new version and will update it here.

**Comment by caiogondim** [comment]
v1.0.5 on [npm](https://www.npmjs.com/package/blooming-menu)
