### ISSUE TITLE
Example for click handlers, links for blooming buttons

### ISSUE THREAD

**Issue by macsupport** [caiogondim/blooming-menu#9]
I like the project, but, for many of us, an example showing an actual click function working for the blooming buttons would be helpful since just having the blooming menu with no function for the buttons makes it not easily usable in a project.

**Comment by caiogondim** [comment]
What you mean by "actual click function".
You should just add an event listener and it should go, like any other HTML element.

You getting some issues with it?

**Comment by macsupport** [comment]
Moved to material-floating-button instead, since there was an example showing how child buttons can be set up as links. Like the project, I just needed a better example as to setting up actual working child menu buttons, no other issues than that.
